//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpOn.Dominio.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HelpOnEntities : DbContext
    {
        public HelpOnEntities()
            : base("name=HelpOnEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Andar> Andar { get; set; }
        public virtual DbSet<Chamado> Chamado { get; set; }
        public virtual DbSet<Gerente> Gerente { get; set; }
        public virtual DbSet<Laboratorio> Laboratorio { get; set; }
        public virtual DbSet<Monitor> Monitor { get; set; }
        public virtual DbSet<Professor> Professor { get; set; }
        public virtual DbSet<Unidade> Unidade { get; set; }
    }
}
