//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpOn.Dominio.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HelpOnEntities : DbContext
    {
        public HelpOnEntities()
            : base("name=HelpOnEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Andar> Andars { get; set; }
        public virtual DbSet<Chamado> Chamadoes { get; set; }
        public virtual DbSet<Gerente> Gerentes { get; set; }
        public virtual DbSet<Laboratorio> Laboratorios { get; set; }
        public virtual DbSet<Monitor> Monitors { get; set; }
        public virtual DbSet<Professor> Professors { get; set; }
        public virtual DbSet<Unidade> Unidades { get; set; }
    }
}
